[tool.poetry]
name = "option"
version = "0.2.5"
description = "Rust like Option and Result types in Python"
authors = ["Peijun Ma <peijun.ma@protonmail.com>"]
readme = "README.md"
license = "MIT"
repository="https://github.com/MaT1g3R/option"
homepage="https://mat1g3r.github.io/option/"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries",
]

include = ['option/py.typed', 'option/**/*.py']

[tool.poetry.dependencies]
python = ">=3.6"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
mypy = "^0.620.0"
Sphinx = "^1.8"
pylint = "^2.1"
pytest-cov = "^2.6"
